WARNING: clusterbot not installed. Can't notify slack.
2021-08-09 09:47:54  Turning off  compiler optimizations for fast compilation
                     Suppressing compiler warnings
                     Running with the following prefs combinations:

                     1 run with default preferences
                     

Running tests in /home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository/frozen_repos/brian2/brian2, /home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository/brian2cuda  (including long tests)
Running Brian version 2.2.2.1+git from '/home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository/frozen_repos/brian2/brian2'
Testing standalone

Testing standalone device "cuda_standalone"
Running standalone-compatible standard tests (single run statement)

==================================== ERRORS ====================================
________ ERROR collecting brian2cuda/tools/testsuite/run_single_test.py ________
/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/py/_path/local.py:704: in pyimport
    __import__(modname)
/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:304: in load_module
    exec(co, mod.__dict__)
/home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository/brian2cuda/tools/test_suite/run_single_test.py:20: in <module>
    ???
utils.py:49: in parse_arguments
    args = parser.parse_args()
/home/denis/.conda/envs/b2c/lib/python2.7/argparse.py:1708: in parse_args
    self.error(msg % ' '.join(argv))
/home/denis/.conda/envs/b2c/lib/python2.7/argparse.py:2378: in error
    self.exit(2, _('%s: error: %s\n') % (self.prog, message))
/home/denis/.conda/envs/b2c/lib/python2.7/argparse.py:2366: in exit
    _sys.exit(status)
E   SystemExit: 2
------------------------------- Captured stderr --------------------------------
usage: run_test_suite.py [-h] [--only {single-run,multi-run,standalone-only}]
                         [--targets [{cuda_standalone,genn,cpp_standalone} [{cuda_standalone,genn,cpp_standalone} ...]]]
                         [--single-precision] [--no-bundles] [--no-atomics]
                         [--num-blocks NUM_BLOCKS] [--all-prefs] [--jobs JOBS]
                         [--dry-run]
                         [test [test ...]]
run_test_suite.py: error: unrecognized arguments: --notify-slack
=============================== warnings summary ===============================
/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/_pytest/mark/structures.py:334
  /home/denis/.conda/envs/b2c/lib/python2.7/site-packages/_pytest/mark/structures.py:334: PytestUnknownMarkWarning: Unknown pytest.mark.cuda_standalone - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
475 deselected, 1 warnings, 1 error in 2.19 seconds
Running standalone-compatible standard tests (multiple run statements)

==================================== ERRORS ====================================
________ ERROR collecting brian2cuda/tools/testsuite/run_single_test.py ________
/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/py/_path/local.py:704: in pyimport
    __import__(modname)
/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:304: in load_module
    exec(co, mod.__dict__)
/home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository/brian2cuda/tools/test_suite/run_single_test.py:20: in <module>
    ???
utils.py:49: in parse_arguments
    args = parser.parse_args()
/home/denis/.conda/envs/b2c/lib/python2.7/argparse.py:1708: in parse_args
    self.error(msg % ' '.join(argv))
/home/denis/.conda/envs/b2c/lib/python2.7/argparse.py:2378: in error
    self.exit(2, _('%s: error: %s\n') % (self.prog, message))
/home/denis/.conda/envs/b2c/lib/python2.7/argparse.py:2366: in exit
    _sys.exit(status)
E   SystemExit: 2
------------------------------- Captured stderr --------------------------------
usage: run_test_suite.py [-h] [--only {single-run,multi-run,standalone-only}]
                         [--targets [{cuda_standalone,genn,cpp_standalone} [{cuda_standalone,genn,cpp_standalone} ...]]]
                         [--single-precision] [--no-bundles] [--no-atomics]
                         [--num-blocks NUM_BLOCKS] [--all-prefs] [--jobs JOBS]
                         [--dry-run]
                         [test [test ...]]
run_test_suite.py: error: unrecognized arguments: --notify-slack
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
655 deselected, 1 error in 1.87 seconds
Running standalone-specific tests

==================================== ERRORS ====================================
________ ERROR collecting brian2cuda/tools/testsuite/run_single_test.py ________
/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/py/_path/local.py:704: in pyimport
    __import__(modname)
/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:304: in load_module
    exec(co, mod.__dict__)
/home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository/brian2cuda/tools/test_suite/run_single_test.py:20: in <module>
    ???
utils.py:49: in parse_arguments
    args = parser.parse_args()
/home/denis/.conda/envs/b2c/lib/python2.7/argparse.py:1708: in parse_args
    self.error(msg % ' '.join(argv))
/home/denis/.conda/envs/b2c/lib/python2.7/argparse.py:2378: in error
    self.exit(2, _('%s: error: %s\n') % (self.prog, message))
/home/denis/.conda/envs/b2c/lib/python2.7/argparse.py:2366: in exit
    _sys.exit(status)
E   SystemExit: 2
------------------------------- Captured stderr --------------------------------
usage: run_test_suite.py [-h] [--only {single-run,multi-run,standalone-only}]
                         [--targets [{cuda_standalone,genn,cpp_standalone} [{cuda_standalone,genn,cpp_standalone} ...]]]
                         [--single-precision] [--no-bundles] [--no-atomics]
                         [--num-blocks NUM_BLOCKS] [--all-prefs] [--jobs JOBS]
                         [--dry-run]
                         [test [test ...]]
run_test_suite.py: error: unrecognized arguments: --notify-slack
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
649 deselected, 1 error in 1.85 seconds
ERROR: 3/3 test suite(s) did not complete successfully (see above).
2021-08-09 09:48:00  
TARGET: CUDA_STANDALONE
2021-08-09 09:48:00  
FINISHED ALL RUNS

                     1/1 CONFIGURATIONS FAILED:
                     	1. run
                     		default preferences
Test suite took 0 h 0 m 7 s.
